# -*- coding: utf-8 -*-
"""Copy of Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bFsBIueEsqZ1jSwOgzjCVeiTiorP-P09

# Welcome to Colab!

---

# **Predictive Analytics for Smart Fertilizer Recommendation**

      **A Data-Driven Machine Learning Approach**


1.1 Executive Summary & Problem Context Objective

To design a robust machine learning pipeline that recommends the most suitable fertilizer based on soil characteristics, crop type, and environmental conditions.

**The Challenge**

Fertilizer selection is a non-trivial decision problem. The relationship between soil nutrients (N, P, K), moisture, climate conditions, and crop type is highly non-linear. Traditional rule-based systems fail to generalize across crops and soil types, often leading to over-fertilization or nutrient imbalance.

**Our Approach**

Instead of building a simplistic classifier, this project emphasizes:

Data Integrity & Encoding Strategy for categorical agronomic features

Model Robustness using ensemble learning

Inference Explainability via feature importance

Real-World Inference Capability through a prediction function
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

"""# 2. Data Acquisition & Integrity Checks

We ingest the fertilizer dataset containing soil, crop, and climate attributes.
In a production system, this data could originate from IoT sensors or agricultural databases.
"""

df = pd.read_csv("/content/Fertilizer Prediction.csv")

print("Dataset Preview")
print(df.head())

"""# **2.1 Data Quality Validation**

**Observation**

The dataset contains no missing values, ensuring reliable downstream modeling.
"""

print("\nMissing Values:")
print(df.isnull().sum())

"""# **3. Exploratory Data Analysis (EDA)**

Before modeling, we validate that the dataset reflects real agricultural diversity.

**Key Insights**

Multiple fertilizer classes → multi-class classification problem

Both numerical and categorical variables → encoding strategy is critical

Nutrient levels and moisture vary significantly across crops

# 4. Feature Engineering Strategy

**4.1 Categorical Encoding Decision**

| Feature         | Cardinality | Strategy       |
| --------------- | ----------- | -------------- |
| Soil Type       | Low         | Label Encoding |
| Crop Type       | Medium      | Label Encoding |
| Fertilizer Name | Target      | Label Encoding |

"""

label_encoders = {}

categorical_cols = ["Soil Type", "Crop Type", "Fertilizer Name"]

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

"""# 5. Feature–Target Definition

Features: Climate + Soil + Nutrients

Target: Fertilizer Category

# 6. Train–Test Split

To ensure generalization:

80% Training

 20% Testing
"""

X = df.drop("Fertilizer Name", axis=1)
y = df["Fertilizer Name"]

# Step 6: Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""# 7.1 Model Training"""

model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

"""# 8. Model Evaluation & Diagnostics
**8.1 Quantitative Metrics**
"""

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("\nModel Accuracy:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

"""**8.2 Confusion Matrix Analysis**"""

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt="d")
plt.title("Confusion Matrix")
plt.show()

"""# 9. Model Reasoning & Explainability
**Feature Importance Analysis**

Interpretation

Crop Type & Soil Moisture dominate predictions

Nutrient levels (N, P, K) strongly influence fertilizer choice

Confirms domain logic → fertilizer depends on crop biology + soil chemistry
"""

importance = pd.Series(model.feature_importances_, index=X.columns)
importance.sort_values().plot(kind="barh", figsize=(8,6))
plt.title("Feature Importance")
plt.show()

"""# 10. Inference Function (Real-World Usage)"""

def predict_fertilizer(temp, humidity, moisture, soil, crop, N, K, P):

    soil_encoded = label_encoders["Soil Type"].transform([soil])[0]
    crop_encoded = label_encoders["Crop Type"].transform([crop])[0]

    input_data = np.array([[temp, humidity, moisture,
                            soil_encoded, crop_encoded,
                            N, K, P]])

    prediction = model.predict(input_data)

    fertilizer = label_encoders["Fertilizer Name"].inverse_transform(prediction)

    return fertilizer[0]
    result = predict_fertilizer(
    temp=30,
    humidity=60,
    moisture=40,
    soil="Loamy",
    crop="Sugarcane",
    N=10,
    K=5,
    P=20
)

print("\nRecommended Fertilizer:", result)

"""# 11. Conclusion & Recommendations

**Key Findings**


1.Fertilizer recommendation is non-linear → Random Forest outperforms linear models


2.Soil moisture and crop type are decisive factors

3.Model is both accurate and interpretable


**Production Recommendations**


1.Integrate real-time weather APIs

2.Extend to fertilizer quantity prediction (regression)

3.Deploy as a farmer-facing web application
"""