# -*- coding: utf-8 -*-
"""Copy of Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bFsBIueEsqZ1jSwOgzjCVeiTiorP-P09

# Welcome to Colab!
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv("/content/Fertilizer Prediction.csv")

print("Dataset Preview")
print(df.head())

print("\nMissing Values:")
print(df.isnull().sum())

label_encoders = {}

categorical_cols = ["Soil Type", "Crop Type", "Fertilizer Name"]

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

X = df.drop("Fertilizer Name", axis=1)
y = df["Fertilizer Name"]

# Step 6: Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("\nModel Accuracy:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt="d")
plt.title("Confusion Matrix")
plt.show()

importance = pd.Series(model.feature_importances_, index=X.columns)
importance.sort_values().plot(kind="barh", figsize=(8,6))
plt.title("Feature Importance")
plt.show()

def predict_fertilizer(temp, humidity, moisture, soil, crop, N, K, P):

    soil_encoded = label_encoders["Soil Type"].transform([soil])[0]
    crop_encoded = label_encoders["Crop Type"].transform([crop])[0]

    input_data = np.array([[temp, humidity, moisture,
                            soil_encoded, crop_encoded,
                            N, K, P]])

    prediction = model.predict(input_data)

    fertilizer = label_encoders["Fertilizer Name"].inverse_transform(prediction)

    return fertilizer[0]
    result = predict_fertilizer(
    temp=30,
    humidity=60,
    moisture=40,
    soil="Loamy",
    crop="Sugarcane",
    N=10,
    K=5,
    P=20
)

print("\nRecommended Fertilizer:", result)